### ISSUE TITLE
Image resize give error when user "resize-image" in nodejs

### ISSUE THREAD

**Issue by RashmiPandey** [csbun/resize-image#1]
Code for image resize is 
var img = "https://cdn-img.com/sites/default/abc.jpg";
var data = resizeImage.resize2Canvas(img, 200, 100);
console.log("data" + data);

And getting this error
ReferenceError: document is not defined
    at Object.resize2Canvas (*****PROJECT FOLDER************\node_modules\resize-image\index.js:51:27)
    at Object.<anonymous> (D:\work\gitlab\route\image-scrape.js:52:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\work\gitlab\server.js:32:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by RashmiPandey** [comment]
Please help me out to solve this issue

**Comment by csbun** [comment]
This package is design for browser as it's Description "Resize images in browser using canvas".
Maybe we can try using [node-canvas](https://github.com/Automattic/node-canvas) in node.js.

**Comment by csbun** [comment]
Try to use [gm](github.com/aheckmann/gm) or [jimp](https://github.com/oliver-moran/jimp) for Node.js
